version: '2'

services:
  box:
    image: busybox
    volumes:
      - /box

  redis:
    image: 'redis:latest'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  # api:
  #   build: ./api
  #   command: bash start
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - './api:/robot_api'
  #   volumes_from:
  #     - box

  bot:
    depends_on:
    build: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/bot'
    environment:
      - LANG=C.UTF-8

volumes:
  box:
  redis:
