version: '2'

services:
  box:
    image: busybox
    volumes:
      - /box

  api:
    build: ./api
    command: bash start
    ports:
      - '3000:3000'
    volumes:
      - './api:/robot_api'
    volumes_from:
      - box

volumes:
  box:
